version: "2"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=secretpassword"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/prepare_db.sh:/usr/local/bin/prepare_db.sh
  postfix:
    build:
      context: ./imgs/postfix
    restart: always
    ports:
      - 587:587
    depends_on:
      - spamassassin
      - mysql
    volumes:
      - ./data/cert:/cert
      - ./data/mail:/home/vmail
  dovecot:
    build:
      context: ./imgs/dovecot
    restart: always
    ports:
      - 993:993
    depends_on:
      - spamassassin
      - mysql
    volumes:
      - ./data/cert:/cert
      - ./data/mail:/home/vmail
  spamassassin:
    build:
      context: ./imgs/spamassassin
    restart: always
  php:
    build:
      context: ./imgs/php
    restart: always
    volumes:
      - ./data/postadmin:/var/www/html
      - ./data/config.inc.php:/var/www/html/config.inc.php
    depends_on:
      - mysql
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./data/postadmin:/var/www/html
      - ./data/config.inc.php:/var/www/html/config.inc.php
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/dhparams.pem:/etc/nginx/dhparams.pem
      - ./data/cert:/cert
      - ./data/known:/known
    ports:
      - 20007:80
    depends_on:
      - php
  certbot:
    build:
      context: ./imgs/certbot
    restart: always
    volumes:
      - ./data/cert:/etc/letsencrypt
      - ./data/known:/known
