version: "2"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=secretpassword"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/prepare_db.sh:/usr/local/bin/prepare_db.sh
  postfix:
    build:
      context: ./imgs/postfix
    restart: always
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    depends_on:
      - spamassassin
      - mysql
    volumes:
      - ./data/cert:/cert
      - ./data/mail:/home/vmail
      - ./data/postfix:/var/spool/postfix
  dovecot:
    build:
      context: ./imgs/dovecot
    restart: always
    ports:
      - "993:993"
      - "995:995"
    depends_on:
      - spamassassin
      - mysql
    volumes:
      - ./data/cert:/cert
      - ./data/mail:/home/vmail
  spamassassin:
    build:
      context: ./imgs/spamassassin
    restart: always
    volumes:
      - ./data/spamassassin:/var/lib/spamassassin
      - ./data/mail:/home/vmail
  php:
    build:
      context: ./imgs/php
    restart: always
    volumes:
      - ./data/webmail:/var/www/html
      - ./data/postadmin:/var/www/html/_postadmin
      - ./data/config.inc.php:/var/www/html/_postadmin/config.inc.php
    depends_on:
      - mysql
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./data/webmail:/var/www/html
      - ./data/postadmin:/var/www/html/_postadmin
      - ./data/config.inc.php:/var/www/html/_postadmin/config.inc.php
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/cert:/cert
      - ./data/known:/known
    ports:
      - "127.0.0.1:20007:80"
    depends_on:
      - php
  certbot:
    build:
      context: ./imgs/certbot
    restart: always
    volumes:
      - ./data/cert:/etc/letsencrypt
      - ./data/known:/known
